# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ubuntu:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update packages
        run: apt update

      - name: Install packages
        run: apt install pev innoextract -y

      - name: Get executable
        run: wget https://www.delldisplaymanager.com/ddmsetup.exe
  

      - name: Extract
        run: innoextract ddmsetup.exe

      - name: ls 
        run: ls -al ./app

      - name: Get Version
        run: peres -v app/ddm.exe | awk '{print $3}'
      
      # Runs a set of commands using the runners shell
      - uses: actions/upload-artifact@v2
        with:
         name: ddm
         path: ./app/ddm.exe
